eldmnet/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'
urlpatterns = [
    path('', views.home, name='index'),
    path('user_login/', views.user_login, name='user_login'),
    path('register/', views.register, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.user_logout, name='logout'), 
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
]

eldmnet/eldmnet/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts'))
]

eldmnet/accounts/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
                      .filter(status=Post.Status.PUBLISHED)

class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'    
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, 
                               on_delete=models.CASCADE,
                               related_name='accounts_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('accounts:post_detail', args=[self.publish.year,
                                                     self.publish.month,
                                                     self.publish.day,
                                                     self.slug])

eldmnet/accounts/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

eldmnet/accounts/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import UserForm
from .models import Post
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.
def home(request):
    post_list = Post.published.all()
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'accounts/base.html', {'posts': posts})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED, slug=post, publish__year=year, publish__month=month, publish__day=day)
    return render(request, 'accounts/post/detail.html', {'post': post})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('accounts:index'))

@login_required
def dashboard(request):
    return render(request, 'accounts/dashboard.html')

def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()
    return render(request, 'accounts/registration.html', {'user_form': user_form,
                                                          'registered': registered})

def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if(user):
            if(user.is_active):
                login(request, user)
                return HttpResponseRedirect(reverse('accounts:dashboard'))
            else:
                return HttpResponse("account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("Username: {} and Password: {}".format(username, password))
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request, 'accounts/login.html', {})

eldmnet/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <title>eldm.net</title>
        <link href="{% static "css/jquery-ui.css" %}" rel="stylesheet">
        <link href="https://fonts.cdnfonts.com/css/glitch-slap" rel="stylesheet">
    </head>
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <script src="{% static 'js/index.js' %}"></script>
    <style>
        body {
            background: #E2E2E2;
            font-family: 'Glitch Slap', sans-serif;
        } 
        .text-color {
            color: #00171c;
        }
        .center {
            text-align: center;
        }
    </style>
    <body>
        <h1 class="ui-accordion-header ui-corner-top ui-accordion-header-collapsed ui-corner-all ui-state-default ui-accordion-icons">
            eldm.net
        </h1>
        <div class="ui-tabs ui-corner-all ui-widget ui-widget-content">
            <ul class="ui-tabs-nav ui-corner-all ui-helper-reset ui-helper-clearfix ui-widget-header">
                <li id="home" class="ui-tabs-tab ui-corner-top ui-state-default ui-tab ui-tabs-active ui-state-active">
                    <a href="{% url 'accounts:index' %}" class="ui-tabs-anchor">Home</a>
                </li>
                {% if user.is_authenticated %}
                <li id="logout" class="ui-tabs-tab ui-corner-top ui-state-default ui-tab">
                    <a href="{% url 'accounts:logout' %}"class="ui-tabs-anchor">Logout</a>
                </li>
                <li id="dashboard" class="ui-tabs-tab ui-corner-top ui-state-default ui-tab">
                    <a href="{% url 'accounts:dashboard' %}"class="ui-tabs-anchor">Dashboard</a>
                </li>
                {% else %}
                <li id="login" class="ui-tabs-tab ui-corner-top ui-state-default ui-tab">
                    <a href="{% url 'accounts:user_login' %}" class="ui-tabs-anchor">Login</a>
                </li>
                <li id="register" class="ui-tabs-tab ui-corner-top ui-state-default ui-tab">
                    <a href="{% url 'accounts:register' %}" class="ui-tabs-anchor">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
        {% block content %}
        {% endblock %}

        {% if request.resolver_match.url_name == 'index' %}
            <h1 class="center">Welcome to the new eldm.net</h1>
            <p class="center">Contained in this site is misc files and blog posts.</p>
            {% for post in posts %}
                <h2>
                    <a href="{{ post.get_absolute_url }}">
                        {{ post.title }}
                    </a>
                </h2>
                <p class="date">
                    Published {{ post.publish }} by {{ post.author }}
                </p>
                {{ post.body|truncatewords:30|linebreaks }}
            {% endfor %}
            {% include "./pagination.html" with page=posts %}
        {% endif %}
        
    </body>
</html>

eldmnet/templates/accounts/dashboard.html
{% extends "accounts/base.html" %}
{% block content %}
    <h2 class="text-color">Hello {{ user.username }} welcome to your dashboard.</h2>
{% endblock %}

eldmnet/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% block content %}
    <h1 class="text-color">Please login</h1>
    <form action="{% url 'accounts:user_login' %}" method="post">
        {% csrf_token %}
        <label class="text-color" for="username">Username: </label>
        <input type="text" name="username" placeholder="Enter Username">
        <label class="text-color" for="password">Password: </label>
        <input type="password" name="password">
        <input type="submit" name="" value="Login">

    </form>
{% endblock %}

eldmnet/templates/accounts/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

eldmnet/templates/accounts/post/detail.html
{% extends "accounts/base.html" %}
{% block title %}{{post.title}}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p>
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|linebreaks }}
{% endblock %}

eldmnet/templates/accounts/registration.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block content %}
    {% if registered %}
        <h1 class="text-color">Thank you for registering</h1>
    {% else %}
        <h1 class="text-color">Register Here</h1>
        <h3 class="text-color">Fill out the form:</h3>
        <form class="text-color" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ user_form.as_p }}
            <input  type="submit" name="" value="Register">
        </form>
    {% endif %}
{% endblock %}